services:
  authentication-db:
    image: postgres:15
    container_name: authentication-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: senhaSegura
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
    - authentication_network

  authentication:
    image: rer-authentication:latest
    build: . # usa o Dockerfile na raiz do projeto (keycloak)
    container_name: authentication
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://authentication-db:5432/keycloak
      KC_DB_URL_HOST: authentication-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: senhaSegura
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_SPI_THEME_CACHE_THEMES: "false"
      KC_SPI_THEME_CACHE_TEMPLATES: "false"
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json # <- Aqui estÃ¡ o IMPORT
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: localhost
      KEYCLOAK_FRONTEND_URL: http://localhost/rectest/keycloak
      KC_HOSTNAME_URL: http://localhost/rectest/keycloak
      KC_HOSTNAME_PATH: /rectest/keycloak
      KC_HOSTNAME_PORT: "443"
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KEYCLOAK_PROFILE: preview
      KC_FEATURES: "scripts"
      KC_CORS: "true"
      QUARKUS_HTTP_CORS_ENABLED: "true"
      QUARKUS_HTTP_CORS_METHODS: "GET,PUT,POST,DELETE,OPTIONS"
    # volumes:
    #   - ./keycloak-import:/opt/keycloak/data/import # <- Monta a pasta local com o export
    depends_on:
      - authentication-db
    command: start --import-realm --optimized
    networks:
      # - frontend_network
      - gateway_network
      - authentication_network

  authentication-frontend:
    image: rer-authentication-frontend:latest
    build: ./frontend
    container_name: authentication-frontend
    depends_on:
      - authentication-backend
    networks:
    - authentication_network
    # - frontend_network
    - gateway_network

  authentication-backend:
    image: rer-authentication-backend:latest
    build: ./cardpg
    container_name: authentication-backend
    depends_on:
      - authentication-db
    networks:
    - authentication_network
    # - frontend_network
    - gateway_network

volumes:
  postgres_data:

networks:
  authentication_network:
    driver: bridge
  # frontend_network:
  #   driver: bridge